# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dok_Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kood', models.CharField(max_length=255)),
                ('korpus', models.CharField(max_length=255)),
                ('tekstikeel', models.CharField(max_length=25)),
                ('tekstityyp', models.CharField(max_length=25)),
                ('elukoht', models.CharField(max_length=25)),
                ('taust', models.CharField(max_length=25)),
                ('vanus', models.CharField(max_length=25)),
                ('sugu', models.CharField(max_length=10)),
                ('emakeel', models.CharField(max_length=25)),
                ('kodukeel', models.CharField(max_length=25)),
                ('keeletase', models.CharField(max_length=5)),
                ('haridus', models.CharField(max_length=10)),
                ('abivahendid', models.CharField(max_length=10)),
            ],
        ),
    ]
