# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171106_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omanikud',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
