# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171106_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='raamatud',
            name='omanikud',
            field=models.ManyToManyField(to='app.omanikud'),
        ),
        migrations.RemoveField(
            model_name='omanikud',
            name='omatud_raamatu_nr',
        ),
        migrations.AddField(
            model_name='omanikud',
            name='omatud_raamatu_nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
