# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('food_item', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('date_added', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
