# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_diary'),
        ('app', '0003_dokarvud_dokmeta'),
    ]

    operations = [
    ]
