# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171106_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raamatud',
            name='id',
        ),
        migrations.AlterField(
            model_name='raamatud',
            name='raamatu_nr',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
